app/models.py
from enum import unique
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import ForeignKey
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()


class Employee(db.Model, UserMixin):
    __tablename__ = 'employees'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    employee_number = db.Column(db.Integer, nullable=False, unique=True)
    hashed_password = db.Column(db.String(255), nullable=False)

    orders = db.relationship('Order', back_populates='employee')

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.hashed_password, password)


class Menu(db.Model):
    __tablename__ = 'menus'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)

    items = db.relationship('MenuItem', back_populates='menu')


class MenuItem(db.Model):
    __tablename__ = 'menu_items'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    price = db.Column(db.Float, nullable=False)
    menu_id = db.Column(db.Integer,
                        db.ForeignKey('menus.id'),
                        nullable=False)
    menu_type_id = db.Column(db.Integer,
                             db.ForeignKey('menu_item_types.id'),
                             nullable=False)

    menu = db.relationship('Menu', back_populates='items')
    type = db.relationship('MenuItemType')


class MenuItemType(db.Model):
    __tablename__ = 'menu_item_types'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)


class Order(db.Model):
    __tablename__ = 'orders'

    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer,
                            db.ForeignKey('employees.id'),
                            nullable=False)
    table_id = db.Column(db.Integer,
                         db.ForeignKey('tables.id'),
                         nullable=False)
    finished = db.Column(db.Boolean, nullable=False)

    employee = db.relationship('Employee', back_populates='orders')
    table = db.relationship('Table', back_populates='orders')
    details = db.relationship('OrderDetail', back_populates='order')

    @property
    def total(self):
        return sum([detail.menu_item.price for detail in self.details])


class OrderDetail(db.Model):
    __tablename__ = 'order_details'

    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer,
                         db.ForeignKey('orders.id'),
                         nullable=False)
    menu_item_id = db.Column(db.Integer,
                             db.ForeignKey('menu_items.id'),
                             nullable=False)

    order = db.relationship('Order', back_populates='details')
    menu_item = db.relationship('MenuItem')


class Table(db.Model):
    __tablename__ = 'tables'

    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.Integer, nullable=False, unique=True)
    capacity = db.Column(db.Integer, nullable=False)

    orders = db.relationship('Order', back_populates='table')

app/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    SelectField,
    SelectMultipleField,
    StringField, SubmitField,
    PasswordField
)
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    employee_number = StringField('Employee number', [DataRequired()])
    password = PasswordField('Password', [DataRequired()])
    submit = SubmitField('Login')


class TableAssignementForm(FlaskForm):
    tables = SelectField('Tables', coerce=int)
    servers = SelectField('Servers', coerce=int)
    assign = SubmitField('Assign')


class MenuItemAssignementForm(FlaskForm):
    menu_item_ids = SelectMultipleField('Menu Items', coerce=int)

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from .config import Configuration
from .models import db, Employee
from .routes import orders, session

app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(orders.bp)
app.register_blueprint(session.bp)
db.init_app(app)

login = LoginManager(app)
login.login_view = 'session.login'


@login.user_loader
def load_user(id):
    return Employee.query.get(int(id))

app/routes/orders.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from ..forms import MenuItemAssignementForm, TableAssignementForm
from ..models import (
    db, Employee, MenuItem, MenuItemType, Order, OrderDetail, Table
)

bp = Blueprint('orders', __name__, url_prefix='')


@bp.route('/')
@login_required
def index():
    form = TableAssignementForm()
    open_tables, servers = open_tables_and_servers()
    form.tables.choices = [(t.id, f"Table {t.number}") for t in open_tables]
    form.servers.choices = [(s.id, s.name) for s in servers]

    orders = Order.query \
        .filter(Order.employee_id == current_user.id) \
        .filter(Order.finished == False)

    menu_items = MenuItem.query.join(MenuItemType) \
                         .order_by(MenuItemType.name, MenuItem.name) \
                         .options(db.joinedload(MenuItem.type))

    foods_by_type = {}
    for menu_item in menu_items:
        if menu_item.type.name not in foods_by_type:
            foods_by_type[menu_item.type.name] = []
        foods_by_type[menu_item.type.name].append(menu_item)

    return render_template('orders.html',
                           form=form,
                           orders=orders,
                           foods_by_type=foods_by_type)


@bp.route('/orders/<int:id>/items', methods=['POST'])
def add_to_order(id):
    form = MenuItemAssignementForm()
    form.menu_item_ids.choices = [(i.id, '') for i in MenuItem.query.all()]
    if form.validate_on_submit():
        order = Order.query.get(id)
        for menu_item_id in form.menu_item_ids.data:
            db.session.add(OrderDetail(order=order, menu_item_id=menu_item_id))
        db.session.commit()
    return redirect(url_for('.index'))


@bp.route('/orders/assign', methods=['POST'])
def assign_table():
    form = TableAssignementForm()
    open_tables, servers = open_tables_and_servers()
    form.tables.choices = [(t.id, f"Table {t.number}") for t in open_tables]
    form.servers.choices = [(s.id, s.name) for s in servers]

    if form.validate_on_submit():
        table_id = request.form.get('tables')
        employee_id = request.form.get('servers')
        order = Order(table_id=table_id, employee_id=employee_id, finished=False)
        db.session.add(order)
        db.session.commit()
    return redirect(url_for('.index'))


@bp.route('/orders/<int:id>/close', methods=['POST'])
def close_table(id):
    order = Order.query.get(id)
    order.finished = True
    db.session.commit()
    return redirect(url_for('.index'))


def open_tables_and_servers():
    tables = Table.query.order_by(Table.number).all()
    open_orders = Order.query.filter(Order.finished == False)
    busy_tables_ids = [order.table_id for order in open_orders]
    open_tables = [table for table in tables if table.id not in busy_tables_ids]
    servers = Employee.query.all()
    return open_tables, servers

app/routes/session.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user
from ..forms import LoginForm
from ..models import Employee

bp = Blueprint('session', __name__, url_prefix='/session')


@bp.route('/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('orders.index'))
    form = LoginForm()
    if form.validate_on_submit():
        empl_number = form.employee_number.data
        employee = Employee.query \
                           .filter(Employee.employee_number == empl_number) \
                           .first()
        if not employee or not employee.check_password(form.password.data):
            return redirect(url_for('.login'))
        login_user(employee)
        return redirect(url_for('orders.index'))
    return render_template('login.html', form=form)


@bp.route('/logout', methods=['POST'])
def logout():
    logout_user()
    return redirect(url_for('.login'))

app/templates/base.html
<html>
  <head>
    {% if title %}
      <title>{{ title }} - Order Up!</title>
    {% else %}
      <title>Welcome to Order Up!</title>
    {% endif %}
  </head>
  <body>
    {% if not current_user.is_anonymous %}
      <form action="{{ url_for('session.logout') }}" method="POST">
        <button type="submit">Logout</button>
      </form>
    {% endif %}
    {% block content %}{% endblock %}
  </body>
</html>

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="{{ url_for('.login') }}">
    {{ form.csrf_token }}
    <div>
        {{ form.employee_number.label }} {{ form.employee_number }}

        {% if form.employee_number.errors %}
            <ul>
                {% for error in form.employee_number.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div>
        {{ form.password.label }} {{ form.password }}

        {% if form.password.errors %}
            <ul>
                {% for error in form.password.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div>{{ form.submit }}</div>
</form>
{% endblock %}

app/templates/orders.html
{% extends "base.html" %}

{% block content %}
    <h1>Order Up!</h1>
    <form action="{{ url_for('.assign_table') }}" method="POST">
        {{ form.csrf_token() }}
        ASSIGN TABLE
        <div>
            {{ form.tables.label }} {{ form.tables }}
            {{ form.servers.label }} {{ form.servers }}
            {{ form.assign }}
        </div>
    </form>
    <table>
        <thead>
            <tr>
                <th>YOUR OPEN ORDERS</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td>Table {{ order.table.number }}</td>
                    <td>
                        ${{ order.total }}
                    </td>
                    <td>
                        <form action="{{ url_for('.close_table', id=order.id) }}" method="POST">
                            {{ form.csrf_token }}
                            <button type="submit">Close table</button>
                        </form>
                    </td>
                    <td>
                        <button form="food-list" formaction="{{ url_for('.add_to_order', id=order.id) }}">
                            Add to order
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <form id='food-list' method="POST">
        {{ form.csrf_token }}
        {% for food_type in foods_by_type %}
            <p>{{ food_type }}</p>
            {% for food_item in foods_by_type[food_type] %}
                <input type="checkbox" name="menu_item_ids" id="item_{{ food_item.id }}" value="{{ food_item.id }}">
                <label for="item_{{ food_item.id }}">{{ food_item.name }}</label>
            {% endfor %}
        {% endfor %}
    </form>
{% endblock %}